#!/usr/bin/python3
def raise_exception():
     5 + "4"
